name: Build
on:
  push:
    branches:
      - ft_debugE2EProblem
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm --prefix users/authservice install
    - run: npm --prefix users/userservice install
    - run: npm --prefix gatewayservice install
    - run: npm --prefix historyservice install
    - run: npm --prefix questionservice install
    - run: npm --prefix roomservice install
    - run: npm --prefix webapp install
    - run: npm --prefix webapp run build
    - run: npm --prefix webapp run test:e2e
    env :
      CI : ""
