name: Deploy on release

on:
  release:
    types: [published]
  push:
    branches:
      - e2e

jobs:
  e2etests:
    name: Execute E2Etests
    runs-on: ubuntu-latest
    steps:
    - name: Executing E2E tests
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          exec bash \-l
          cd ~
          echo "Node.js version: $(node --version) npm version: $(npm --version)"
          wget https://raw.githubusercontent.com/arquisoft/wiq_es05c/master/docker-compose.yml -O docker-compose.yml
          wget https://raw.githubusercontent.com/arquisoft/wiq_es05c/master/.env -O .env
          docker compose --profile prod down
          sudo rm -r ./e2e
          git clone https://github.com/Arquisoft/wiq_es05c.git e2e
          cd e2e
          git checkout e2e # Acordarse de eliminar esto en main
          git status
          export GITHUB_ACTIONS=true
          echo "The value of GITHUB ACTIONS is: $GITHUB_ACTIONS"
          echo "Building authservice"
          npm --prefix users/authservice install
          echo "Building userservice"
          npm --prefix users/userservice install
          echo "Building gatewayservice"
          npm --prefix gatewayservice install
          echo "Building historyservice"
          npm --prefix historyservice install
          echo "Building questionservice"
          npm --prefix questionservice install
          echo "Building roomservice"
          npm --prefix roomservice install
          echo "Building webapp"
          npm --prefix webapp install
          npm --prefix webapp run build
          echo "Executing E2E test suite"   
          npm --prefix webapp run test:e2e

